baseurl: '/'
permalink: pretty
title: 'BVJ Science Centre'

logo:
  mobile: "images/logo/logo-mobile.ico"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.png"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_activities: 6

collections:
  activities:
    output: true
    sort_by: weight
    permalink: /:collection/:title:output_ext
  facilities:
    output: true
    sort_by: weight
    permalink: /:collection/:title:output_ext
  galleries:
    output: true
    sort_by: weight
    permalink: /:collection/:title:output_ext
  team:
    output: true
    permalink: /:collection/:title:output_ext
  posts:
    output: true
    permalink: /events/:title:output_ext


defaults:
  - scope:
      path: ""
      type: "activities"
    values:
      layout: "activity"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "eventpage"
  - scope:
      path: ""
      type: "galleries"
    values:
      layout: "gallery"

sass:
  style: compressed # possible values: nested expanded compact compressed

#plugins:
#  - jekyll-environment-variables
#  - jekyll-cloudinary

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: pretty 

#developer_mode: true  

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

cloudinary:
  cloud_name: "dxnndq0qu"
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1280
      fallback_max_width: 800
      steps: 4
      sizes: "(min-width: 50rem) 50rem, 90vw"
